### ISSUE TITLE
feature "pool" is disabled

### ISSUE THREAD

**Issue by oiwn** [dahomey-technologies/rustis#24]
Hello there, impressive work!

I have problem launching example with pool through `bb8`

with dependencies like this

```toml
[dependencies]
rustis = { version = "0.11.0", features = ["pool", "redis-bloom", "tokio-runtime"] }
tokio = { version = "1.27.0", features = ["full"] }
```
and code

```rust
use rustis::Result;
#[cfg(feature = "pool")]
use rustis::{client::PooledClientManager, commands::StringCommands};

#[tokio::main]
async fn main() -> Result<()> {
    #[cfg(feature = "pool")]
    {
        let manager = PooledClientManager::new("127.0.0.1:6379")?;
        let pool = rustis::bb8::Pool::builder()
            .max_size(10)
            .build(manager)
            .await?;

        let client1 = pool.get().await.unwrap();
        client1.set("key1", "value1").await?;
        let value: String = client1.get("key1").await?;
        println!("value: {value:?}");

        let client2 = pool.get().await.unwrap();
        client2.set("key2", "value2").await?;
        let value: String = client2.get("key2").await?;
        println!("value: {value:?}");
    }

    Ok(())
}
```

rust-analyzer wrote me that code is inactive since feature "pool" is disabled. Which is strange since i added it to the dependencies.
